In [1]:
# !pip install scanpy anndata h5py

## Read perturbation data

In [1]:
import scanpy as sc

In [2]:
adata = sc.read_h5ad('RPE1_CRISPRa_mean_pop.h5ad')

In [3]:
adata

AnnData object with n_obs × n_vars = 10912 × 5424
    obs: 'protospacer', 'target_gene', 'target_expr', 'active', 'cluster', 'cluster_name', 'cluster_description', 'gene_driven', 'sequence_driven', 'sequence_suffix', 'bulk_expr', 'expressed', 'p_expressed', 'de_genes', 'strength', 'cell_count', 'target_gene_id', 'masked_active', 'masked_cluster', 'masked_cluster_name', 'masked_cluster_description', 'masked_cluster_size', 'masked_cluster_num_genes', 'stricter_masked_cluster', 'stricter_masked_cluster_description'
    var: 'feature_types', 'genome', 'mean', 'in_matrix', 'std', 'cv', 'fano', 'pairwise_p_cost', 'mean_adjusted_pairwise_p_cost', 'excess_cv', 'pairwise_chosen', 'gene_id'
    layers: 'adj_p', 'masked', 'p'

In [4]:
adata.X[:3, :3]

array([[-0.20237759,  0.32916796,  0.36707863],
       [ 0.1216391 , -0.18778017,  0.10134853],
       [-0.17349932,  0.04407395, -0.13333985]])

In [5]:
adata.obs

protospacer target_gene  \
guide_identity                                                      
AATF_GCGCAGAAGGTTGAAGGGAT        GCGCAGAAGGTTGAAGGGAT        AATF   
AATF_GCGTGCGAGTGCGCGGGAAG        GCGTGCGAGTGCGCGGGAAG        AATF   
AATF_GGAAGCGCGCAGAAGGTTGA        GGAAGCGCGCAGAAGGTTGA        AATF   
AATF_GGAAGGGATTGGAGCCGTAT        GGAAGGGATTGGAGCCGTAT        AATF   
AATF_GGGCGTTGCTAGCATGAAGG        GGGCGTTGCTAGCATGAAGG        AATF   
...                                               ...         ...   
off-target_GGGAACAGGGGCGGTCCGTA  GGGAACAGGGGCGGTCCGTA  off-target   
off-target_GTAAATTCTCGCGTAACGTT  GTAAATTCTCGCGTAACGTT  off-target   
off-target_GTCCATAGGGTCTAGCGCCG  GTCCATAGGGTCTAGCGCCG  off-target   
off-target_GTGGATTATCTGACGCGAAT  GTGGATTATCTGACGCGAAT  off-target   
off-target_GTTGATCGACCGATTGCGAT  GTTGATCGACCGATTGCGAT  off-target   

                                 target_expr  active  cluster cluster_name  \
guide_identity                                                               
AATF_GCGCAGAAGGTTGAAGGGAT           2.898099   False    372.0          NaN   
AATF_GCGTGCGAGTGCGCGGGAAG           1.635568   False    918.0          NaN   
AATF_GGAAGCGCGCAGAAGGTTGA           2.614520    True   2187.0       AATF_1   
AATF_GGAAGGGATTGGAGCCGTAT           1.581901    True   2187.0       AATF_1   
AATF_GGGCGTTGCTAGCATGAAGG           2.612676   False   1112.0          NaN   
...                                      ...     ...      ...          ...   
off-target_GGGAACAGGGGCGGTCCGTA          NaN   False    161.0          NaN   
off-target_GTAAATTCTCGCGTAACGTT          NaN   False   2142.0          NaN   
off-target_GTCCATAGGGTCTAGCGCCG          NaN   False    395.0          NaN   
off-target_GTGGATTATCTGACGCGAAT          NaN   False   2307.0          NaN   
off-target_GTTGATCGACCGATTGCGAT          NaN   False    584.0          NaN   

                                               cluster_description  \
guide_identity                                                       
AATF_GCGCAGAAGGTTGAAGGGAT        372: SEQUENCE-driven (GGGAT) (13)   
AATF_GCGTGCGAGTGCGCGGGAAG                    singleton (GGAAG) (1)   
AATF_GGAAGCGCGCAGAAGGTTGA                        2187: neither (6)   
AATF_GGAAGGGATTGGAGCCGTAT                        2187: neither (6)   
AATF_GGGCGTTGCTAGCATGAAGG                    singleton (GAAGG) (1)   
...                                                            ...   
off-target_GGGAACAGGGGCGGTCCGTA                  161: neither (45)   
off-target_GTAAATTCTCGCGTAACGTT                  2142: neither (7)   
off-target_GTCCATAGGGTCTAGCGCCG    395: SEQUENCE-driven (CCG) (48)   
off-target_GTGGATTATCTGACGCGAAT                 2307: neither (39)   
off-target_GTTGATCGACCGATTGCGAT                   584: neither (7)   

                                 gene_driven  sequence_driven sequence_suffix  \
guide_identity                                                                  
AATF_GCGCAGAAGGTTGAAGGGAT              False             True           GGGAT   
AATF_GCGTGCGAGTGCGCGGGAAG              False            False                   
AATF_GGAAGCGCGCAGAAGGTTGA              False            False                   
AATF_GGAAGGGATTGGAGCCGTAT              False            False                   
AATF_GGGCGTTGCTAGCATGAAGG              False            False                   
...                                      ...              ...             ...   
off-target_GGGAACAGGGGCGGTCCGTA        False            False                   
off-target_GTAAATTCTCGCGTAACGTT        False            False                   
off-target_GTCCATAGGGTCTAGCGCCG        False             True             CCG   
off-target_GTGGATTATCTGACGCGAAT        False            False                   
off-target_GTTGATCGACCGATTGCGAT        False            False                   

                                 ...  cell_count   target_gene_id  \
guide_identity                   ...                                
AATF_GCGCAGAAGGTTGAAGGGAT 

In [6]:
adata.var

feature_types  genome      mean  in_matrix       std  \
gene_name                                                                
DPM1            Gene Expression  GRCh38  0.497299       True  0.738486   
CFH             Gene Expression  GRCh38  0.278384       True  0.554464   
FUCA2           Gene Expression  GRCh38  0.905370       True  1.024018   
NIPAL3          Gene Expression  GRCh38  0.327920       True  0.624273   
LAS1L           Gene Expression  GRCh38  0.263869       True  0.530470   
...                         ...     ...       ...        ...       ...   
AC010642.2      Gene Expression  GRCh38  0.609991       True  0.836759   
SCO2            Gene Expression  GRCh38  0.259892       True  0.526850   
POLR2J3         Gene Expression  GRCh38  0.579630       True  0.874262   
BX890604.2      Gene Expression  GRCh38  0.288508       True  0.568470   
AUXG01000058.1  Gene Expression  GRCh38  0.207367       True  0.577206   

                      cv      fano  pairwise_p_cost  \
gene_name                                             
DPM1            1.484995  1.096648              NaN   
CFH             1.991723  1.104338              NaN   
FUCA2           1.131049  1.158215        -2.451047   
NIPAL3          1.903735  1.188450              NaN   
LAS1L           2.010355  1.066434              NaN   
...                  ...       ...              ...   
AC010642.2      1.371755  1.147828        -2.582480   
SCO2            2.027185  1.068022              NaN   
POLR2J3         1.508309  1.318657        -2.655410   
BX890604.2      1.970376  1.120100              NaN   
AUXG01000058.1  2.783493  1.606649              NaN   

                mean_adjusted_pairwise_p_cost  excess_cv pairwise_chosen  \
gene_name                                                                  
DPM1                                      NaN   0.977718           False   
CFH                                       NaN   1.006758           False   
FUCA2                                0.066219   0.958416           False   
NIPAL3                                    NaN   1.046037           False   
LAS1L                                     NaN   0.996978           False   
...                                       ...        ...             ...   
AC010642.2                           0.019873   0.981516           False   
SCO2                                      NaN   0.988185           False   
POLR2J3                             -0.042057   1.058342           False   
BX890604.2                                NaN   1.023031           False   
AUXG01000058.1                            NaN   1.222856           False   

                        gene_id  
gene_name                        
DPM1            ENSG00000000419  
CFH             ENSG00000000971  
FUCA2           ENSG00000001036  
NIPAL3          ENSG00000001461  
LAS1L           ENSG00000001497  
...                         ...  
AC010642.2      ENSG00000283103  
SCO2            ENSG00000284194  
POLR2J3         ENSG00000285437  
BX890604.2      ENSG00000285756  
AUXG01000058.1  ENSG00000286214  

[5424 rows x 12 columns]

### Get median/mean expression vector for a particular tf

In [7]:
import pandas as pd
import numpy as np

In [8]:
tf = "ABL1"
i = np.where(adata.obs["target_gene"] == tf)[0]

In [9]:
i

array([ 6,  7,  8,  9, 10, 11])

In [10]:
adata.X[i]

array([[-0.14416087, -0.20047128,  0.1179117 , ...,  0.19370419,
        -0.14405836, -0.31302094],
       [ 0.30330485,  0.87921369, -0.43741891, ...,  0.25068986,
        -0.42807591, -0.11558768],
       [ 0.05258105,  0.13426816,  0.16000102, ...,  0.42708683,
         0.0738101 , -0.0474382 ],
       [-0.10911067,  0.53156996,  0.06052482, ...,  0.00665249,
        -0.25820985,  0.47226983],
       [ 0.22861245,  0.01790708,  0.13218588, ..., -0.00307888,
        -0.12758186,  0.35302222],
       [-0.21573652, -0.02555884,  0.00716345, ..., -0.18514054,
        -0.17881331,  0.02759999]])

In [11]:
expression_vector = np.median(adata.X[i], axis=0)

In [12]:
expression_vector

array([-0.02826481,  0.07608762,  0.08921826, ...,  0.10017834,
       -0.16143584, -0.00991911])

In [13]:
adata.obs["active"].value_counts(normalize=True)

active
False    0.935942
True     0.064058
Name: proportion, dtype: float64

## See contents of gff file (annotations on the genome, from which we can get particular gene sequences)

In [14]:
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.max_colwidth', None)  # do NOT truncate long text fields

In [15]:
gff = pd.read_csv(
    "GRCh38_latest_genomic.gff",
    sep="\t",
    comment="#",
    header=None,
    names=["seqid", "source", "type", "start", "end", "score", "strand", "phase", "attributes"]
)

# Filter to only genes
genes = gff[gff["type"] == "gene"]
print(genes.head())

           seqid      source  type  start    end score strand phase  \
19  NC_000001.11  BestRefSeq  gene  17369  17436     .      -     .   
28  NC_000001.11      Gnomon  gene  29774  35418     .      +     .   
33  NC_000001.11  BestRefSeq  gene  30366  30503     .      +     .   
38  NC_000001.11  BestRefSeq  gene  34611  36081     .      -     .   
45  NC_000001.11  BestRefSeq  gene  65419  71585     .      +     .   

                                                                                                                                                                                                    attributes  
19             ID=gene-MIR6859-1;Dbxref=GeneID:102466751,HGNC:HGNC:50039,miRBase:MI0022705;Name=MIR6859-1;description=microRNA 6859-1;gbkey=Gene;gene=MIR6859-1;gene_biotype=miRNA;gene_synonym=hsa-mir-6859-1  
28                                                ID=gene-MIR1302-2HG;Dbxref=GeneID:107985730,HGNC:HGNC:52482;Name=MIR1302-2HG;description=MIR1302-2 host g

In [16]:
# Find rows whose attributes mention a particular gene, e.g., ABL1
aatf_rows = genes[genes["attributes"].str.contains("Name=ABL1", case=False, na=False)]
print(aatf_rows)

                seqid      source  type      start        end score strand  \
2266930  NC_000009.12  BestRefSeq  gene  130713043  130887675     .      +   

        phase  \
2266930     .   

                                                                                                                                                                                                                                                     attributes  
2266930  ID=gene-ABL1;Dbxref=GeneID:25,HGNC:HGNC:76,MIM:189980;Name=ABL1;description=ABL proto-oncogene 1%2C non-receptor tyrosine kinase;gbkey=Gene;gene=ABL1;gene_biotype=protein_coding;gene_synonym=ABL,BCR-ABL,bcr/abl,c-ABL,c-ABL1,CHDSKM,JTK7,p150,v-abl  


In [17]:
genes.columns

Index(['seqid', 'source', 'type', 'start', 'end', 'score', 'strand', 'phase',
       'attributes'],
      dtype='object')

### Using seqid, start, end to extract sequence

In [42]:
# !pip install pyfaidx
# !pip install Bio

In [18]:
from pyfaidx import Fasta
from Bio.Seq import Seq

genome = Fasta("GRCh38_latest_genomic.fna")

In [19]:
seqid = aatf_rows.iloc[0]["seqid"]
start = aatf_rows.iloc[0]["start"]
end = aatf_rows.iloc[0]["end"]
strand = aatf_rows.iloc[0]["strand"]

seq = str(genome[seqid][start-1:end])  # -1 because pyfaidx is 0-based

if strand == "-":
	seq = str(Seq(str(seq)).reverse_complement())
	

print(len(seq))
print(seq[:200])

174633
AATCCATCATGGCGGCCGCGGGGTTTGGTGTCTGTGCCTGAGCAGCGCTGGAGCCGGAGCCGGTTCCCGGGTCCTGCGGCTGAGGAGCCCCTCCGCTGTCCACGGCCCCTACCGGCGGGGGGCGGCTGGGTCCCTCGGCGGAGCTCGGGAGATGTGACTGCCTGAGGGCGGTGGTGGTGTCAGCGTCCGGGGCCGGGGGA


#### Alternative: consider only the promoter region, 2000 bp up and downstream of transcription start site (TSS)

In [20]:
tss = start if strand == "+" else end

promoter_start = max(0, tss - 2000 - 1)  # -1 for 0-based
promoter_end = tss + 2000

promoter_seq = str(genome[seqid][promoter_start:promoter_end])
if strand == "-":
	promoter_seq = str(Seq(str(promoter_seq)).reverse_complement())

print(promoter_seq[:100])


CTGGGATGAAATTGTGACTCTGTCACACATTGGCCAAGTGACCTTGGGTAGGTAAGTCACatctctgtttccccatctgtattATGGGGAATAGTATTAC
